name: Daily Stats Sync

# Se lance tous les jours à 2h00 UTC (4h00 en France)
on:
  schedule:
    - cron: '0 2 * * *'
  
  # Permet de lancer manuellement depuis GitHub
  workflow_dispatch:

jobs:
  sync-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run daily stats sync
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        ZONE_ID: ${{ secrets.ZONE_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: node scripts/sync-daily-stats.js